version: "3"

services:
    pygeoapi:
        image: geopython/pygeoapi:latest
        environment:
            - POSTGRES_PASS=${POSTGRES_PASS}
            - URL=${URL}
            - DB_HOSTNAME=${DB_HOSTNAME}
        volumes:
            - ./pygeoapi-config.yml:/pygeoapi/local.config.yml
            - ./custom_process:/pygeoapi/pygeoapi/custom_process
            - ./data:/data
        ports:
            - "5000:80"
